version: '2'
services:
  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'dev_hrvsm'

  #webapp:
   # build: './Grafana'
    #container_name: 'grafana'
    #ports:
     # - '3000:3000'
